### ISSUE TITLE
TabbedPage

### ISSUE THREAD

**Issue by bcaceiro** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#13] opened 2019-08-18 20:51 UTC
I've been messing around with your sample so far (congratz! :D )  noticed one thing: using a TabbedPage as MainPage, doesn't allow to share transitions when navigating.

**Comment by GiampaoloGabba** [comment] 2019-08-18 20:58
Hello, thank you for taking your time to play with the plugin :)
Do you mind to share your sample project so i can take a look? It should work if you put the SharedTransitionNavigationPage inside the tab and then navigate (inside the NavigationPage) with standard push&pop.

But i tried it very quickly with an old version so i need to double check things

**Comment by bcaceiro** [comment] 2019-08-18 21:12
Will do. I'm making an iOS AppStore clone, hence the tabs. Just grabbed your repo and started editing the Sample App as it was. Will put it into Github and then I'll send you the link

**Comment by dlmcdonald** [comment] 2019-08-19 05:00
I was able to reproduce this as well using the sample application. I just added a new tabbed page and added the DynamicSampleFrom2 page to it. Then in the MainPage.xaml, I just changed the navigation command like this:
`<Button Text="Collectionview (multiple items)"  Command="{prism:NavigateTo 'MainTabbedPage?selectedTab=DynamicSampleFrom2'}" />`

**Comment by GiampaoloGabba** [comment] 2019-08-19 13:17
@dlmcdonald Shared Transitions  needs to be encapsuled in a SharedTransitionNavigationPage.

So you should have something like this in your main tabbedpage:

```
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
xmlns:sharedTransitions="clr-namespace:Plugin.SharedTransitions;assembly=Plugin.SharedTransitions"
......
/>

        <sharedTransitions:SharedTransitionNavigationPage Title="Test" Icon="testIcon">
            <x:Arguments>
                <pages:DynamicSampleFrom2/>
            </x:Arguments>
        </sharedTransitions:SharedTransitionNavigationPage>

....
other pages
....
</TabbedPage>
```

Then in your App.Xaml you should do this:

`NavigationService.NavigateAsync("TabbedPage/SharedTransitionNavigationPage/DynamicSampleFrom2")`

**Note:
This code is not tested, is just an example written quickly**

Now the DynamicSampleFrom2 can transition to DynamicSampleTo2 with shared animations (or at least should be).
I'm working on shell now, but i will update the repo with an example with tabbedpages, and if i found something not working i'll fix it

**Comment by IeuanWalker** [comment] 2019-09-09 11:35
@GiampaoloGabba Did you get it working with shell?

**Comment by GiampaoloGabba** [comment] 2019-09-13 10:24
@IeuanWalker 
Yep, there is a branch dedicated to shell, it need some more work to avoid minor glitches and a bit of polishing. I plan to update it in the next few weeks!

**Comment by IeuanWalker** [comment] 2019-09-13 10:54
@GiampaoloGabba Perfect thanks :) We are doing a big redesign of out app at the moment (including updating to Xamarin shell), so be nice to include this package as part of that. Could you update this issue once the shell version is released?

**Comment by viniciuslln** [comment] 2019-11-11 00:49
@GiampaoloGabba
Hello, I tried SharedTransitionNavigationPage within Tabbed page like you suggested (without prism) but it does not work.

Would you have another suggestion or better wait for shell support?

**Comment by alexgg94** [comment] 2020-04-05 18:36
Any update on this? It's still not working (without prism).

**Comment by GiampaoloGabba** [comment] 2020-04-08 19:50
Hello, this is fixed on the next version, its coming very soon!

**Closed as completed by GiampaoloGabba** 2020-04-08 19:50 UTC
Labels: bug

**Comment by isax5** [comment] 2020-05-12 19:34
Nice, I'm waiting for it!

**Comment by isax5** [comment] 2020-05-12 19:34
> Hello, this is fixed on the next version, its coming very soon!

Nice, I'm waiting for it!

**Comment by vniehues** [comment] 2020-08-29 17:42
> @dlmcdonald Shared Transitions needs to be encapsuled in a SharedTransitionNavigationPage.
> 
> So you should have something like this in your main tabbedpage:
> 
> ```
> <TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
> xmlns:sharedTransitions="clr-namespace:Plugin.SharedTransitions;assembly=Plugin.SharedTransitions"
> ......
> />
> 
>         <sharedTransitions:SharedTransitionNavigationPage Title="Test" Icon="testIcon">
>             <x:Arguments>
>                 <pages:DynamicSampleFrom2/>
>             </x:Arguments>
>         </sharedTransitions:SharedTransitionNavigationPage>
> 
> ....
> other pages
> ....
> </TabbedPage>
> ```
> 
> Then in your App.Xaml you should do this:
> 
> `NavigationService.NavigateAsync("TabbedPage/SharedTransitionNavigationPage/DynamicSampleFrom2")`
> 
> **Note: This code is not tested, is just an example written quickly**
> 
> Now the DynamicSampleFrom2 can transition to DynamicSampleTo2 with shared animations (or at least should be).
> I'm working on shell now, but i will update the repo with an example with tabbedpages, and if i found something not working i'll fix it

Sorry for commenting on this closed issue but i see a problem with the current implementation for tabbed pages & prism.
When im using your syntax:
`NavigationService.NavigateAsync("TabbedPage/SharedTransitionNavigationPage/DynamicSampleFrom2")`
there is an animation playing when showing that page. 
I'd prefer to use just the normal prism/xf syntax:
`NavigationService.NavigateAsync("TabbedPage")`
`NavigationService.NavigateAsync("TabbedPage?selectedTab=DynamicSampleFrom2")`

however, using this syntax only shows a blank white page for me while your syntax shows the desired result but with an animation i dont want.. 

**any** input is appreciated!

**Comment by vniehues** [comment] 2020-08-29 17:48
Sorry! 

The culprit seems to be 
`NavigationService.NavigateAsync("/TabbedPage")`
notice the **/** indicating an absolute syntax.

`NavigationService.NavigateAsync("TabbedPage")`
gives me the desired page but it is wrapped within a SharedTransitionNavigationPage from the stack before and **does not** show shared transitions.

**Comment by vniehues** [comment] 2020-08-29 17:56
Another update: 
using 
`NavigationService.NavigateAsync("TabbedPage/SharedTransitionNavigationPage/DynamicSampleFrom2")`
results in the tabbed page being opened in a modal. when i pass in "UseModalNavigation: false", it just doesn't navigate at all.
