### ISSUE TITLE
[Bug] Navigation.PopAsync(false) results in empty page

### ISSUE THREAD

**Issue by Inrego** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#45] opened 2020-08-29 13:14 UTC
## Bug Information

Version Number of Plugin: 2.3.0
Device Tested On: Android 10.0
Simulator Tested On: Nope
Version of VS: VS 2019
Version of Xamarin: 4.8.0.1269
Versions of other things you are using:

### Steps to reproduce the Behavior
Call `Navigation.PopAsync(false);`

### Expected Behavior
Page is popped without any animations

### Actual Behavior
Page is popped, but now the current page is empty.

**Comment by VladimirFelix** [comment] 2020-08-31 07:16
I had the same issue but only in iOS devices, also if I go back with a gesture the animation is beggin and if go back with pop the animations don't work.
In Android works fine.

![ezgif com-resize](https://user-images.githubusercontent.com/5857023/91693763-6093c800-eb20-11ea-8695-6aaad12ff7ae.gif)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5857023/91694457-69d16480-eb21-11ea-8e2a-470145cb82ee.gif)

**Comment by GiampaoloGabba** [comment] 2020-09-24 13:45
ok, i think that disabling the animation will disable entirely my custom delegate, so the view that got animated are not getting rendered, i can fix that.

@VladimirFelix  do you have the same problem or your is different? 
To be clear, hwne you pop get a blank page, or when you pop the backwards animation doesnt start and there is the standard animation instead?

**Comment by GiampaoloGabba** [comment] 2020-09-27 15:16
the non-animated pop is fixed in the next version.

@VladimirFelix regarding your issue with iOS i cant reproduce it. Would you mind to open a new issue and post a repro? Thx!

**Closed as completed by GiampaoloGabba** 2020-09-27 15:16 UTC
Labels: bug

**Comment by GiampaoloGabba** [comment] 2020-09-27 15:25
ok, if ound the issue in iOS, it's happening with shell. opening a new issue

**Comment by VladimirFelix** [comment] 2020-09-27 19:34
> ok, if ound the issue in iOS, it's happening with shell. opening a new issue

yes, I’m using shell :)

**Comment by GiampaoloGabba** [comment] 2020-09-27 19:39
Oh man... with the new xf updates pop & gesture are complety broken... trying to find a way  to fix it but everything in xf is internal and is a real challenge trying to work with an api like this....

________________________________
Da: Hugo Vladimir Felix Anaya <notifications@github.com>
Inviato: Sunday, September 27, 2020 9:35:06 PM
A: GiampaoloGabba/Xamarin.Plugin.SharedTransitions <Xamarin.Plugin.SharedTransitions@noreply.github.com>
Cc: Giampaolo Gabba <info@evolutionlab.it>; State change <state_change@noreply.github.com>
Oggetto: Re: [GiampaoloGabba/Xamarin.Plugin.SharedTransitions] [Bug] Navigation.PopAsync(false) results in empty page (#45)


ok, if ound the issue in iOS, it's happening with shell. opening a new issue

yes, I’m using shell :)
